const value = {
    nome= null,
    cpf= null,
    data_nascimento= null,
    nome_mae= null,
    sexo= null,
    nomes_homonimos= null,
    status= null,
    endereco= null,
    bairro= null,
    cidade= null,
    estado= null,
    tel_comercial= null,
    tel_celular= null,
    tel_residencial= null,
    endereco= null,
    telefone= null,
    data= null,
    pendencias_comerciais= null,
    pendencias_bancarias= null,
    cheque_fundo= null,
    protestos= null,
    acoes_juridicas= null,
    falencias= null,
    dividas_vencidas= null,
    pendencias_internas= null,
    data= null,
    segmento= dados[756],
    empresa= null,
    cnpj= null,
    ano_fundacao= null,
    data_ultima_atualizacao= null,
    participacao= null,
    uf= null,
    data_ultima_atualizacao_cadastral= null,
    nome= null,
    cpf= null,
    rg= null,
    orgao= dados[6],
    uf= null,
    data_emissao= null,
    data_nascimento= null,
    uf_nascimento= null,
    estado_civil= null,
    dependentes= null,
    escolaridade= null,
    valor_escore= null,
    chance_pagamento= null
}

const objCnpj = async()=> {
    let values = value

        values.nome= dados[1698]
        values.cpf= dados[1731]
        values.data_nascimento= dados[1700]
        values.nome_mae= dados[354]
        values.sexo= dados[1782]
        values.nomes_homonimos= dados[6]
        values.status= dados[344]
        values.endereco= dados[453]
        values.bairro= dados[421]
        values.cidade= dados[456]
        values.estado= dados[6]
        values.tel_comercial= dados[6]
        values.tel_celular= dados[6]
        values.tel_residencial= dados[6]
        values.endereco= dados[0]
        values.telefone= dados[6]
        values.data= dados[6]
        values.pendencias_comerciais= dados[630]
        values.pendencias_bancarias= dados[698]
        values.cheque_fundo= dados[824]
        values.protestos= dados[867]
        values.acoes_juridicas= dados[936]
        values.falencias= dados[6]
        values.dividas_vencidas= dados[970]
        values.pendencias_internas= dados[6]
        values.data= dados[757]
        values.segmento= dados[756]
        values.empresa= dados[1225]
        values.cnpj= dados[1243]
        values.ano_fundacao= dados[6]
        values.data_ultima_atualizacao= dados[1247]
        values.participacao= dados[1248]
        values.uf= dados[6]
        data_ultima_atualizacao_cadastral= dados[0]
        values.nome= dados[1869]
        values.cpf= dados[6]
        values.rg= dados[383]
        values.orgao= dados[6]
        values.uf= dados[6]
        values.data_emissao= dados[6]
        values.data_nascimento= dados[6]
        values.uf_nascimento= dados[472]
        values.estado_civil= dados[388]
        values.dependentes= dados[486]
        values.escolaridade= dados[394]
        values.valor_escore= dados[0]
        values.chance_pagamento= dados[6]

}

module.exports = { objCnpj }

